version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 790768631355.dkr.ecr.us-east-1.amazonaws.com/nestjsapp
      - REPOSITORY_URI=790768631355.dkr.ecr.us-east-1.amazonaws.com/nestjsapp
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - cd example-apps/nestjs-cloud/app/
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"NestJsApp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > ../../../imagedefinitions.json
      - cat ../../../imagedefinitions.json
      - ls -al
      - ls -al ../../../
      - pwd
artifacts:
  files:
    - './imagedefinitions.json'
  name: imagedefinitions.json
